FROM python:3.9-slim-buster

LABEL description="Rock, Paper, Scissors переводится как Камень, Ножницы, Бумага."

WORKDIR /app

COPY RockPaperScissorsGame.py /app

CMD ["python", "/app/RockPaperScissorsGame.py"]
